package tests;

public class TestData {
    public static final String SIMBOLS_1000 = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Cras egestas justo metus, non venenatis urna fermentum eget. Nam ante sem, suscipit ut tellus id, efficitur tempus orci. Vestibulum quis neque accumsan ipsum ornare pulvinar eu sed velit. Ut mauris purus, malesuada sed nulla sed, rutrum interdum massa. Suspendisse malesuada quam urna, commodo cursus lorem vehicula a. Nunc ac sodales arcu. Nullam pulvinar purus eu erat egestas imperdiet. Cras egestas tortor vel elit vehicula rhoncus. Aliquam vitae iaculis quam. Praesent eleifend facilisis leo, sagittis volutpat magna condimentum eu. Cras id pellentesque nibh. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam nec risus vel nibh finibus consectetur eget ac sem. Integer libero lorem, vulputate a maximus ac, posuere et ante. Proin non metus et diam elementum vestibulum et vel tortor." +
            "" +
            "Duis sollicitudin nisi risus. Maecenas dui lectus, consequat ut ullamcorper placerat, dapibus vel enim. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Aliquam porttitor sed ligula ultrices laoreet. Vivamus gravida finibus risus id egestas. Sed eu libero dui. Suspendisse convallis quam ut vestibulum condimentum. Vestibulum vel vulputate arcu." +
            "" +
            "Duis non elit quis lectus egestas rhoncus vehicula at mi. Aenean cursus placerat aliquet. Nulla vestibulum, nisl non rutrum euismod, sem tellus interdum sem, quis tempor massa odio sed ligula. Curabitur auctor leo eu magna ornare feugiat. Quisque eleifend ex turpis, quis porta ipsum consectetur eget. Nunc viverra nec nisl a vestibulum. Maecenas nec enim bibendum, posuere erat ut, laoreet tortor. Mauris fermentum posuere risus a ornare. Fusce accumsan varius felis in posuere. Quisque ante metus, pulvinar eget nisl vel, tincidunt malesuada felis. Sed nulla nibh, tristique non enim vel, blandit tempus erat." +
            "" +
            "In aliquet, lectus ac rutrum pharetra, ipsum nibh cursus mi, non tristique elit neque nec ante. Morbi ac mauris id elit ornare sodales. Donec sed dapibus tortor. Vestibulum mollis, odio sit amet mattis rhoncus, tortor nibh consequat arcu, sed finibus massa mi sit amet urna. Mauris at gravida ligula. Donec vel aliquam dui. Sed dictum id risus eget tincidunt. Fusce sed elit ac turpis pellentesque dictum vel a ex. Ut eget sagittis ante, vitae mollis sapien. Sed ultrices dolor in mollis hendrerit." +
            "" +
            "In tempus quis nisi nec sollicitudin. Morbi in eleifend sem. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Cras nec orci dolor. Suspendisse purus erat, ullamcorper sit amet magna a, imperdiet tincidunt tortor. Mauris blandit ornare turpis pulvinar tristique. Maecenas egestas nulla et est finibus, nec aliquet justo dictum. Nulla non commodo leo, non laoreet ante. Suspendisse placerat, urna imperdiet varius cursus, lectus est blandit mauris, semper gravida nibh enim dignissim ligula. Donec pellentesque nulla quis dignissim tincidunt." +
            "" +
            "Aliquam semper ante ipsum, nec dignissim lacus pharetra non. Praesent nec tincidunt erat, sit amet imperdiet odio. Fusce auctor tellus erat, quis facilisis mauris elementum id. Proin eget interdum dui, et congue tellus. Donec commodo finibus viverra. Integer non tortor augue. Etiam sit amet erat dictum, pulvinar nulla dictum, dapibus nisi." +
            "" +
            "In ac felis ut est mollis maximus. Vestibulum nec lacus ante. Nulla fringilla enim vel fermentum ullamcorper. Fusce a eleifend nisl, id congue turpis. Donec pharetra, leo non ullamcorper lobortis, eros ligula venenatis purus, sed placerat ligula magna eu nibh. Cras pharetra porta libero quis faucibus. Integer mollis nunc quis diam scelerisque pharetra. Fusce pellentesque scelerisque odio sed egestas. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec pharetra consectetur dictum. Aenean pulvinar nibh est, nec dictum ipsum luctus at. Nulla hendrerit quam vitae lacus pulvinar, ac interdum lectus lobortis. Nam eget consectetur ipsum. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Etiam sed tristique tortor." +
            "" +
            "Donec eu lobortis lectus. Pellentesque rhoncus consectetur erat, non convallis velit imperdiet et. Fusce sed facilisis ante, sagittis fringilla ante. Nam ac nulla id leo egestas venenatis nec quis lectus. Praesent dapibus metus vitae erat congue dapibus. Suspendisse id libero id est mattis dignissim. Nulla ultricies augue ultrices sem sodales posuere. Pellentesque efficitur eros non odio hendrerit, sed gravida purus tincidunt. Aliquam diam neque, rutrum id ultricies sed, malesuada fermentum felis. Donec sodales vestibulum est vel aliquam. Pellentesque sem arcu, efficitur sit amet lacus eu, bibendum commodo nisl. Sed luctus odio ac tellus volutpat tincidunt. Vivamus sed varius mi." +
            "" +
            "Vestibulum odio mi, commodo dictum erat sed, fermentum vestibulum enim. In sed erat ac lectus vulputate aliquet scelerisque non leo. Curabitur nisi urna, sagittis a varius et, hendrerit a tortor. Sed lectus ligula, dapibus sit amet magna non, pharetra cursus arcu. Donec quis augue vehicula, pellentesque turpis non, porta odio. Vivamus pharetra, dolor in eleifend pretium, nulla purus fermentum erat, vitae luctus dolor lacus quis nunc. Quisque nec faucibus est. Sed posuere nisi non mi feugiat luctus. Cras sit amet scelerisque ante. Integer sit amet tellus ac massa vestibulum convallis. Nulla quis lectus tellus. Ut vestibulum lorem nec tincidunt iaculis. Vestibulum at dictum libero." +
            "" +
            "Mauris eu feugiat sapien. Nam volutpat rutrum leo, quis auctor tellus viverra vel. Morbi tincidunt ligula in eros accumsan, sed sollicitudin diam feugiat. Aenean ac justo ut elit pulvinar molestie. Morbi et dapibus metus. Sed malesuada ex sapien, et placerat dui luctus non. Phasellus augue tortor, viverra dictum tempor sit amet, consequat non arcu. Quisque quis rutrum diam. Duis iaculis porttitor enim, sit amet dignissim lorem feugiat et." +
            "" +
            "Aliquam lacinia, dui faucibus mollis suscipit, orci ligula lacinia justo, vel porttitor sapien lectus fermentum nisi. Donec vestibulum vitae arcu et rutrum. Sed nec hendrerit risus. Praesent malesuada molestie ornare. Donec vitae sapien ac augue tincidunt sodales. Pellentesque egestas ultrices sodales. Nullam placerat arcu ac lorem maximus egestas. Vivamus non ex sed leo tristique venenatis eget vitae nunc. Etiam varius ipsum a turpis consequat, eu molestie mauris bibendum. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Proin nunc eros, iaculis bibendum rhoncus vitae, bibendum a orci." +
            "" +
            "Donec quis lacinia ipsum, a vestibulum erat. Donec in ex et sapien rhoncus feugiat vitae nec lorem. Proin pellentesque gravida eros at rutrum. Vestibulum ut fermentum quam, ac aliquam leo. Donec accumsan magna.";
}

